services:
  - type: web
    name: toxic-detector-ai
    env: python
    region: oregon
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    branch: main
