services:
  - type: web
    name: toxic-detector-ai
    env: python
    region: oregon  # or frankfurt if you're in EU
    plan: free
    branch: main  # or your default branch
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
