services:
  - type: web
    name: toxicity-ai-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    runtime: python
    repo: https://github.com/ParaNoid0809/toxic-detector-ai
    branch: main
    autoDeploy: true
